import { useState } from "react";
import CyberCard from "../components/CyberCard";

function AttackInfo() {
  const [openIndex, setOpenIndex] = useState(null);

  const attacks = [
    { name: "DoS (Denial of Service)", description: "A DoS attack happens when a single attacker sends a huge number of requests or traffic to a target system, making it slow or unavailable for normal users." },
    { name: "DDoS (Distributed Denial of Service)", description: "A DDoS attack is similar to DoS, but it is launched from many compromised systems at the same time. This makes the attack much more powerful and difficult to stop." },
    { name: "Brute Force Attack", description: "A brute force attack tries many usernames and passwords repeatedly until the correct one is found. It is commonly used against login systems." },
    { name: "Port Scanning", description: "Port scanning is used by attackers to discover which ports are open on a system. Open ports may reveal services that can later be attacked." },
    { name: "SQL Injection", description: "SQL Injection is a web attack where malicious SQL queries are inserted into input fields. It can allow attackers to access, modify, or delete database data." },
    { name: "XSS (Cross-Site Scripting)", description: "XSS is an attack where malicious scripts are injected into a web page. When users open the page, the script runs in their browser and can steal data or sessions." },
    { name: "MITM (Man-in-the-Middle)", description: "In a MITM attack, the attacker secretly intercepts communication between two parties. The attacker may read, alter, or capture sensitive data during transmission." },
    { name: "Phishing Attack", description: "Phishing tricks users into revealing sensitive information such as passwords, OTPs, or banking details through fake emails, websites, or messages." },
    { name: "Malware Traffic", description: "Malware traffic is suspicious communication generated by infected systems. It may contact attacker-controlled servers, steal data, or spread malicious software." },
    { name: "DNS Spoofing", description: "DNS spoofing redirects users to fake websites by providing false DNS responses. Users may think they are visiting a trusted site while actually reaching a malicious one." },
    { name: "ARP Spoofing", description: "ARP spoofing occurs in local networks when an attacker sends fake ARP messages to associate their device with another system's IP address, often enabling traffic interception." },
    { name: "SYN Flood", description: "A SYN flood attack sends many TCP connection requests without completing the handshake. This fills up server resources and prevents valid users from connecting." }
  ];

  const toggleAttack = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 gap-4">
        {attacks.map((attack, index) => (
          <CyberCard key={index} className="overflow-hidden p-0">
            <button
              onClick={() => toggleAttack(index)}
              className="w-full px-5 py-4 text-left flex items-center justify-between font-semibold text-lg cyber-button rounded-none border-0"
            >
              <span>{attack.name}</span>
              <span className="text-xl">{openIndex === index ? "−" : "+"}</span>
            </button>

            {openIndex === index && (
              <div className="px-5 py-4 text-sm leading-7 text-slate-300 bg-slate-800/50">
                {attack.description}
              </div>
            )}
          </CyberCard>
        ))}
      </div>
    </div>
  );
}

export default AttackInfo;